books/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from django import views
from django.urls.conf import include
from home import views
import home 
from .views import *



def new_func():
    return path
app_name = "books"
urlpatterns = [
    path("",  indexView.as_view(), name="index"),
    path("about", views.about , name='about'),
    path("howitworks", views.howitworks , name='howitworks'),
   path("category/", views.category, name="category"),
    path("products/<int:myid>", views.productView, name="ProductView"),
    path("addtocart/<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    
    path("mycart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),
    

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    path("search/", SearchView.as_view(), name="search"),
    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),
    path("sell/", SellView.as_view(), name="sell"),

   # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),


]

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE ,default="")
    full_name = models.CharField(max_length=60 ,default="")
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20 ,default="")

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE ,default="")
    full_name = models.CharField(max_length=200 ,default="")
    address = models.CharField(max_length=200, null=True, blank=True ,default="")
    joined_on = models.DateTimeField(auto_now_add=True)
    phone=models.PositiveIntegerField(default=0 ,max_length=10)

    def __str__(self):
        return self.full_name

class Profile(models.Model):
    user = models.OneToOneField(Customer ,on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    otp = models.CharField(max_length=6)

class Category(models.Model):
    title = models.CharField(max_length=200 ,default="")
    
    


    def __str__(self):
        return self.title



class Product(models.Model):
    title = models.CharField(max_length=200 ,default="")
    product_type=models.CharField(max_length=300, null=True, blank=True ,default="")
    category = models.ForeignKey(Category, on_delete=models.CASCADE )
    condition = models.CharField(max_length=300, null=True, blank=True ,default="")
    language= models.CharField(max_length=300, null=True, blank=True ,default="")
    price_range= models.CharField(max_length=300, null=True, blank=True ,default="")
    binding= models.CharField(max_length=300, null=True, blank=True ,default="")
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField(default=0)
    selling_price = models.PositiveIntegerField(default=0)
    description = models.TextField(default="")
    warranty = models.CharField(max_length=300, null=True, blank=True ,default="")
    return_policy = models.CharField(max_length=300, null=True, blank=True ,default="")
    view_count = models.PositiveIntegerField(default=0)
    
    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(id__in =ids)

    @staticmethod
    def get_all_products():
        return Product.objects.all()


    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        else:
            return Product.get_all_products();
    
    def __str__(self):
        return self.title

    

class UsedProduct(models.Model):
    title = models.CharField(max_length=200 ,default="")
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE )
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField(default=0)
    selling_price = models.PositiveIntegerField(default=0)
    description = models.TextField(default="")
    warranty = models.CharField(max_length=300, null=True, blank=True ,default="")
    return_policy = models.CharField(max_length=300, null=True, blank=True ,default="")
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=0)
    subtotal = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200 ,default="")
    shipping_address = models.CharField(max_length=200 ,default="")
    mobile = models.CharField(max_length=10 ,default="")
    email = models.EmailField(null=True, blank=True ,default="")
    subtotal = models.PositiveIntegerField(default=0)
    discount = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS ,default="")
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/addtocart.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Add To Cart{% endblock %}
{% block content %}
<style>
.h42{
    margin-top: 100px;
    margin-left: 250px;
    margin-right: 50px;
    margin-bottom: 100px;
  width: 50%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<p class="h42"> Product Added To Cart <p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
      <title>WYN- buy and sell books </title>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!--enable mobile device-->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!--fontawesome css--> 
      <link rel="stylesheet" href="{%static 'website/css/font-awesome.min.css'%}">
      <!--bootstrap css-->
      <link rel="stylesheet" href="{%static 'website/css/bootstrap.min.css'%}">
      <!--animate css-->
      <link rel="stylesheet" href="{%static 'website/css/animate-wow.css' %}">
      <!--main css-->
      <link rel="stylesheet" href="{%static 'website/css/style.css'%}">
      <link rel="stylesheet" href="{%static 'website/css/bootstrap-select.min.css'%}">
      <link rel="stylesheet" href="{%static 'website/css/slick.min.css'%}">
      <!--responsive css-->
      <link rel="stylesheet" href="{%static 'website/css/responsive.css'%}">

     


</head>
<style>
.bbt{
   display:flex;
   
}
</style>

<body>
   <header id="header" class="top-head">
         <!-- Static navbar -->
         <nav class="navbar navbar-default">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-md-4 col-sm-12 left-rs">
                     <div class="navbar-header">
                        <button type="button" id="top-menu" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"> 
                        <span class="sr-only">Toggle navigation</span> 
                        <span class="icon-bar"></span> 
                        <span class="icon-bar"></span> 
                        <span class="icon-bar"></span> 
                        </button>
                        <!-- {%static 'website/images/'%}-->
                        <a href="/" class="navbar-brand"><img src="{%static 'website/images/w1.jpg'%}" alt="" /></a>
                     </div>
                     <form class="navbar-form navbar-left web-sh" action="{% url 'books:search' %}" method="GET">
                        <div class="bbt"  >
                           <input name="keyword" type="search" class="form-control" placeholder="Search for product" required>
                          <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button> 
                        </div>
                     </form>
                     
                  </div>
                  <div class="col-md-8 col-sm-12">
                     <div class="right-nav">
                     
                        <div class="login-sr">
                           <div class="login-signup">
                           
           
            
            
                              <ul><li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'books:customerprofile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'books:customerlogout' %}"> Logout </a>
                {% else %}
                <a class="dropdown-item" href="{% url 'books:customerregistration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'books:customerlogin' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
            
                   
           </div>
        </div>
              
                             


                        <div class="help-r hidden-xs">
                           <div class="help-box">
                              <ul>
                              <li> <a href="/contact"><img class="h-i" src="{%static 'website/images/images/help-icon.png'%}" alt="" /> help </a> </li>
                               <li>
                                 
                               <a href="{% url 'books:mycart'  %}"> <button type="button"   class="btn btn-primary" data-toggle="modal" data-target="#cart">Cart</button> </a>
                                 
                                </li>
                                 
                                 
                                
                              </ul>
                           </div>
                        </div>
                        <div class="nav-b hidden-xs">
                           <div class="nav-box">
                              <ul>
                                 <li><a href="\howitworks">How it works</a></li>
                                 <li><a href="\about">about us</a></li>
                                 
                              </ul>
                           </div>
                        </div>
                        
                     </div>
                     
                  </div>
                  
               </div>
               
            </div>
            <!--/.container-fluid --> 
            
         </nav>
      </header>
      <!-- Modal -->
 

      </div>
      <div id="sidebar" class="top-nav">
         <ul id="sidebar-nav" class="sidebar-nav">
            <li><a href="/contact">contact</a></li>
            <li><a href="howitworks.html">How it works</a></li>
            <li><a href="#">WYN for Business</a></li>
         </ul>
      </div>

 {% block content %}
    {% endblock %}


      <footer>
         <div class="main-footer">
            <div class="container">
               <div class="row">
                  <div class="footer-top clearfix">
                     <div class="col-md-2 col-sm-6">
                        <h2>Start a free
                           account today
                        </h2>
                     </div>
                     <div class="col-md-6 col-sm-6">
                        <div class="form-box">
                           <input type="text" placeholder="Enter yopur e-mail" />
                           <button>Continue</button>
                        </div>
                     </div>
                     <div class="col-md-4 col-sm-12">
                        <div class="help-box-f">
                           <h4>Question? Call us on 12 34 56 78 for help</h4>
                           <p>Easy setup - no payment fees </p>
                        </div>
                     </div>
                  </div>
                  <div class="footer-link-box clearfix">
                     <div class="col-md-6 col-sm-6">
                        <div class="left-f-box">
                           <div class="col-sm-4">
                              <h2>SELL ON WYN</h2>
                              <ul>
                                 <li><a href="/register/">Create account</a></li>
                                 <li><a href="/howitworks">How it works suppliers</a></li>
                                 
                              </ul>
                           </div>
                           <div class="col-sm-4">
                              <h2>BUY ON WYN</h2>
                              <ul>
                                 <li><a href="/register/">Create account</a></li>
                                 <li><a href="/howitworks">How it works buyers</a></li>
                                 <li><a href="/category">Categories</a></li>
                                 
                              </ul>
                           </div>
                           <div class="col-sm-4">
                              <h2>COMPANY</h2>
                              <ul>
                                 <li><a href="/about">About WYN</a></li>
                                 <li><a href="/about-us.html">Contact us</a></li>
                                 
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-6">
                        <div class="right-f-box">
                           <h2>BOOKS WE HAVE</h2>
                           <ul class="col-sm-4">
                              <li><a href="/category">ICSE </a></li>
                              <li><a href="/category">CBSE </a></li>
                              <li><a href="/category">JEE MAIN</a></li>
                              <li><a href="/category">JEE ADVANCE</a></li>
                              <li><a href="/category">NEET</a></li>
                           </ul>
                           <ul class="col-sm-4">
                              <li><a href="/category">ENGINEERING</a></li>
                              <li><a href="/category">MEDICAL</a></li>
                              <li><a href="/category">PHARMACY</a></li>
                              <li><a href="/category">ARTS</a></li>
                              <li><a href="/category">BUISNESS & FINANCE</a></li>
                           </ul>
                           <ul class="col-sm-4">
                              <li><a href="/category">NOVELS</a></li>
                              <li><a href="/category">UPSC</a></li>
                              <li><a href="/category">SSC</a></li>
                              <li><a href="/category">MANY MORE</a></li>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="copyright">
            <div class="container">
               <div class="row">
                  <div class="col-md-8">
                     <p><img width="90" src="{%static 'website/images/w1.jpg'%}" alt="#" style="margin-top: -5px;" /> All Rights Reserved. Company Name © 2018</p>
                  </div>
                  <div class="col-md-4">
                     <ul class="list-inline socials">
                        <li>
                           <a href="">
                           <i class="fa fa-facebook" aria-hidden="true"></i>
                           </a>
                        </li>
                        <li>
                           <a href="">
                           <i class="fa fa-twitter" aria-hidden="true"></i>
                           </a>
                        </li>
                        <li>
                           <a href="">
                           <i class="fa fa-instagram" aria-hidden="true"></i>
                           </a>
                        </li>
                        <li>
                           <a href="#">
                           <i class="fa fa-linkedin" aria-hidden="true"></i>
                           </a>
                        </li>
                     </ul>
                     <ul class="right-flag">
                        <li><a href="#"><img src="{%static 'website/images/TIR.png'%}" width="20px" height="20px" alt="" /> <span>Ind</span></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </footer>


   
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}


        {% block content %}


      <style>
         .ls{
            	background: #09294c;
               font-color:white;
              
         }
         
             
         

         .container2{
             margin-top: 50px;
             margin-left: 70px;
             
             
         }
         h2,h3{
             text-align: center;
             margin-top: 15px;
             margin-bottom: 15px;
              text-shadow: 2px 2px 2px #CCCCCC;
               font-weight: bold; letter-spacing: -1px;
         }
        
         
      </style>
     

   
<h2>CHECKOUT</h2>
<div class="container1">
<div class="container2" >
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'books:mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST" >
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 500px;
  height: 500px;
  margin: 100px;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
  
}

.con {
  border: none;
  outline: 0;
  margin-bottom:5px;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #09294c;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
  
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}


.ppic{
    height:350px;
}
.cont{
    display:flex;
}
.status{
    margin:100px;
}
</style>


<div class="cont">

<div class="card">
<img src="{%static 'website/images/profile.jpg'%}" alt="" style="width:100%" class="ppic">
  <h1>{{customer.full_name}}</h1>
  <p class="title">Username: </span> {{customer.user.username}}</p>
  <p class="other">Address:{{customer.address}}</p>
  <p>Joined on: {{customer.joined_on}}</p>
  
  <p class="con">Contact:{{customer.user.email}}<br> {{customer.phone}}</p>
</div>

<div class="status col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href=""> #ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

      
   {% block content %}

   <style>
         .ls{
            	background: #09294c;
               font-color:white;
              
         }

         .container1{
             margin-left: 30%;
             margin-top:50px;
         }
        
        h3{
             
            margin-top: 15px;
            margin-bottom: 15px;
            text-shadow: 2px 2px 2px #CCCCCC;
            font-weight: bold; letter-spacing: -1px;
         }
         
      </style>
     
      
      
      	<div class="container1">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3> Login </h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Customer</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            <p>Forgot Password?<a href="/forgot-password/">Reset now.</a></p>
            <p> or dont have account? <a href="/register{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Sign Up</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/mycart.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}


{% block content %}
 <style>
         .ls{
            	background: #09294c;
               font-color:white;
              
         }
      </style>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                           <a href="{% url 'books:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'books:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'books:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>

                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'books:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="/checkout"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/otp.html
{% extends "base.html" %}
{% block content %}



<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your number {{mobile}}</h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

templates/passwordreset.html
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Reset password</button>
            </form>
        </div>
    </div>
</div>

templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<style>.polaroid {
  width: 30%;
  background-color: white;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  margin-bottom: 25px;
}

.baby {
  text-align: center;
  padding: 10px 20px;
}

.betemoj,.usp{
   display: flex;
   margin-left: 300px;
   flex-wrap: wrap;
   justify-content: space-around;
}
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            <div class="betemoj">     
                  
                      {% for result in results %}
                          <div class="polaroid" > 
                           <a > <img src='/media/{{result.image}}'  alt="Norther Lights" style="width:100%"></a>
                          <div class="baby">
                          <p><h4>{{result.title}}</h4></p>
                          <p><span></span></p>
                         <strike> <h3>Rs. {{result.marked_price}} </h3> </strike>
                         <h3>Rs. {{result.selling_price}} </h3>
                         <span id="divpr{{result.id}}" class="divpr">
                           <!--<button id="pr{{i.id}} "type="button" class="btn btn-primary cart">Add to Cart</button>-->
                           <a href="/addtocart/{{result.id}}" data-name="{{result.title}}" data-price="{{result.selling_price}}" class="add-to-cart btn btn-primary">Add to cart</a>
                         </span>
                         <a href="/product/{{result.id}}"><button id="qv{{result.id}}" class="btn btn-primary cart">Quick View</button></a>
                          </div>
                         </div>
                     {% endfor %}
                   </div>  
                    </div>  
                    </div>  
                    </div>  
                   {% endblock %}